### ISSUE TITLE
Device tracker disparue.

### ISSUE THREAD

**Issue by WarC0zes** [Cyr-ius/hass-livebox-component#56]
Bonjour après la maj du core 2022.2.0, toutes les entité device tracker sont devenu indisponible. Et regardant ca m'a créer de nouvelle entité pour les device tracker avec le  même nom et un _2 a la fin. J'ai désinstaller l'intégration et réinstaller. Maintenant toutes les entités device tracker existe plus. Voila les seul entité créer:

![livebox](https://user-images.githubusercontent.com/91471397/152288982-4f3ae38c-18d6-4a18-8c36-ecbf6fb8b145.jpg)

Ce qui est bizarre c'est qui n'y a pas d'entité visible dans l'intégration, mais elles ont l'air disponible.

ex:
![tracker](https://user-images.githubusercontent.com/91471397/152290025-81efe432-14d0-4543-aa6f-badf8c7b694f.jpg)

```
[device_tracker.pc_477]
PC-477
not_home	
source_type: router
ip_address: null
first_seen: null
friendly_name: PC-477
```
Il y a des changements dans le nouveau core qui ont du cassé quelque chose.
D'autre personne ont le problème ?

Désoler mais il y pas de log.

**Comment by papo-o** [comment]
idem pour moi après la maj du core 2022.2.0

**Comment by Aohzan** [comment]
C'est "voulu" niveau core : https://www.home-assistant.io/blog/2022/02/02/release-20222/#improved-handling-of-device-tracker-entities

**Comment by papo-o** [comment]
pour les équipements inconnus oui mais théoriquement les devices_tracker générés précédemment devrait continuer de fonctionner car connus non?

**Comment by WarC0zes** [comment]
me suis trompé de bouton, je close pas ;)

**Comment by WarC0zes** [comment]
le pire c'est que je voit les entité dans historique mais toute absente et indisponible dans l'integration. Pas mal le délire.
![tracker2](https://user-images.githubusercontent.com/91471397/152333146-9caf5517-e6a0-46f0-8700-284b6ec28874.jpg)

**Comment by WarC0zes** [comment]
> C'est "voulu" niveau core : https://www.home-assistant.io/blog/2022/02/02/release-20222/#improved-handling-of-device-tracker-entities

c'est voulu ok, mais on devrait pouvoir activer les entités, mais elle n'existe pas.

**Comment by Aohzan** [comment]
j'ai pas trop regardé, mais je pense qu'il faut maj le code pour remonter à nouveau les entités (spécifier la propriété `mac_address` et non plus de `device_info` si j'ai bien compris), voir la PR en question https://github.com/home-assistant/core/pull/63328

**Comment by geobar78** [comment]
Not fixed by 2022.2.1

I try to add (don't know if it was a good idea but want to try something at my level)

device_tracker:
    - platform: livebox

And here after the error log:

Logger: homeassistant.setup
Source: components/device_tracker/legacy.py:303
First occurred: 06:27:57 (1 occurrences)
Last logged: 06:27:57

Error during setup of component device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/__init__.py", line 50, in async_setup
    await async_setup_legacy_integration(hass, config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 158, in async_setup_integration
    legacy_platforms = await async_extract_config(hass, config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 303, in async_extract_config
    raise ValueError(
ValueError: Unable to determine type for livebox: None

**Comment by geobar78** [comment]
En attendant si ça peut aider je suis passé sur du Ping tracker, un peu fastidieux à configurer du coup mais rien d'impossible.

**Comment by Cyr-ius** [comment]
Bonjour  à tous, 
la version 1.7.2 fraichement sortie  corrige le problème de device tracker
J'en ai profité pour ajouter l'information sur la mac address.

**Comment by geobar78** [comment]
Super boulot, je te confirme que ça fonctionne à nouveau et j'en profite également pour te confirmer que ça fonctionne sur livebox5 :)

**Comment by WarC0zes** [comment]
Super taf, tout refonctionne. Merci beaucoup pour c'est maj. Je cloture.
